# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - laravel-sqlite-api-swagger-DW

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_34da0b9ec63e45d69f34c9bf9fe69f2f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4ea90a7757154506b0eb775748e265f8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_34da0b9ec63e45d69f34c9bf9fe69f2f }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'laravel-sqlite-api-swagger-DW'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_72cf211b2d814b3385ec8e6f58dbdb7f }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_34da0b9ec63e45d69f34c9bf9fe69f2f }}/appsvc/staticsite:${{ github.sha }}'